### ISSUE TITLE
does main_test demo work or not? 

### ISSUE THREAD

**Issue by gulmezmerve** [CTSRD-CHERI/FreeRTOS-Demos-CHERI-RISC-V#4]
hi, 
I am trying to do experiment, unfortunately it seems main_tests demo cannot compile. Print capability doesn't work, does someone still update this repo? or cherifreertos is abondaned

**Comment by heshamelmatary** [comment]
@gulmezmerve That's now addressed I believe (on Slack) and you could build/run it fine

**Comment by gulmezmerve** [comment]
yeah, exactly; thanks for the support; 

Here is my takeaway: 

- CheriFreeRTOS is currently on ./cheribuild.y hmka2 branch. 

- That requires an LLVM-specific branch, too; if you already have an LLVM build, make sure that you start with a fresh build one. 

- The make_tests example program uses the capabilities. The [readme](https://github.com/CTSRD-CHERI/FreeRTOS-Demos-CHERI-RISC-V) file shows the non-capabilities build version. Please use the `./cheribuild.py freertos-baremetal-riscv64-purecap` version

- main_tests example program using DEBUG features, you can compile with `-DNDEBUG=1`
